# 测试环境配置
services:
  app:
    image: ${DOCKERHUB_USERNAME:-yourusername}/proxylab:develop
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./data/subscription_converter_staging.db
      - SECRET_KEY=${STAGING_SECRET_KEY:-staging-secret-key}
      - DEBUG=true
      - LOG_LEVEL=debug
      - HOST=0.0.0.0
      - PORT=8001
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONIOENCODING=utf-8
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - app-network
    ports:
      - "8001:8001"

  frontend:
    image: ${DOCKERHUB_USERNAME:-yourusername}/proxylab-frontend:develop
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:80"

networks:
  app-network:
    driver: bridge
