# Docker Compose 文件 - 整合镜像（包含Nginx和FastAPI）

services:
  app:
    image: 1136623363/proxylab:latest
    ports:
      - "8899:80"    # 统一端口（Nginx代理）
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书（可选）
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/subscription_converter.db}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - HOST=0.0.0.0
      - PORT=8001
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONIOENCODING=utf-8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.5'
        reservations:
          memory: 768M
          cpus: '0.75'

volumes:
  data:
  logs:
